Added ability to add parameters of type xml and Guid. Added ability t…
bl-tools/postgre-fluent-sql-wrapper pull request #4
Opened 2020-09-29 15:10 UTC by kubasm989

Added ability to add parameters of type xml and Guid.
Added ability to retrieve multiple datasets from single stored procedure.

2020-09-29 18:50 UTC, dreadfuljohndow commented
Hi, Please add an example - how to use your changes, you can add it to the README.md file

2020-09-29 19:29 UTC, kubasm989 commented
Hi, I updated the README.md file. Please let me know if you would like any other examples.

2020-09-30 08:32 UTC, dreadfuljohndow requested changes

2020-09-30 08:32 UTC, dreadfuljohndow commented on src/BlTools.PostgreFluentSqlWrapper/FluentSqlCommand.cs
> +		private void ExecStoredProcedureMultiSet()
fix empty space

2020-09-30 08:32 UTC, dreadfuljohndow commented on src/BlTools.PostgreFluentSqlWrapper/FluentSqlCommand.cs
> +		private void ExecStoredProcedureMultiSet()
would be nice to have an async version

2020-09-30 08:32 UTC, dreadfuljohndow commented on src/BlTools.PostgreFluentSqlWrapper/FluentSqlCommand.cs
> +                                        _dataReaderActionMultiSet?.Invoke(reader, setNumber);
If I understand correctly you are going to implement something like a 'switch' in the reader function, and fill data by number.
I think it is not a stable code, if the order of results will be changed → you will need to change the reader
I think would be nice to associate the readFunction with the cursor's name and call it by name, instead return a number.
it can be solved by returning the name of the cursor instead number or by using a list of readers - List<KeyValuePair<string, Func< IDataReader>>>

2020-09-30 08:32 UTC, dreadfuljohndow commented on src/BlTools.PostgreFluentSqlWrapper/FluentSqlCommand.cs
> +            // multi set only supported for stored procedures retrieving data sets
exception with this comment as a message?
using exception you will get fast feedback about the wrong call

2020-09-30 20:40 UTC, closed without merging